### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by KapteinBabbalas**
I fixed the onMesageReceived events and missing field in FMessageIdentifierKey

### CODE REVIEW

**Comment by janpieterz** [comment]
@KapteinBabbalas thanks for your pull request. Could you try to remove your personal phone number from the commit?

**Comment by KapteinBabbalas** [comment]
@janpieterz I saw that , I committed a new version to overwrite the values, but how to I remove the incorrect commit ? commit d76e68a5b29bbf3fcc74679e51c32058ea44da36

**Comment by janpieterz** [comment]
@KapteinBabbalas this link seems to describe the method. To be honest I've never done it myself either, but it seems like a good idea not to make something this personal available for everyone ;)

http://stackoverflow.com/questions/1338728/delete-commits-from-a-branch-in-git

**Comment by KapteinBabbalas** [comment]
I saw that ! :-)
I did remove it , it doesn't show

**Comment by KapteinBabbalas** [comment]
@sanderdriesen I screwed up here, will you delete this thread please. I will send you a new pull request - without my own number in it :-)

**Comment by janpieterz** [comment]
@KapteinBabbalas we can't delete a pull request, only close it. We could ask the staff but I don't give that a big chance (http://stackoverflow.com/questions/18318097/delete-a-closed-pull-request-from-github).

Could you remove the commit from your local repository? And did you try a push head with force after that? The only way we can get rid of this commit is by you removing it, if that is possible. I can close it but that's it.

**Comment by KapteinBabbalas** [comment]
Hi

I did close the pull request, and just deleted my branch and started from
scratch.

**Comment by janpieterz** [comment]
@KapteinBabbalas I know, thanks for that, but we can't delete a pull request, that is impossible. I can only lock it. The only way to remove your phone number from this is by you executing the git commands.

**Pull request closed without merging**
